
title: Irispeng
email: pengaman@outlook.com 
description: > # this means to ignore newlines until "baseurl:"
    This is just another Jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pengaman.github.io" # the base hostname & protocol for your site
github:  https://github.com/pengaman


# Build settings
markdown: kramdown
encoding: utf-8
paginate: 3
paginate_path: "page:num"


gems: [jekyll-paginate] 
